app_index:
  path: /
  methods: GET
  defaults: { _controller: AppBundle:Api:welcome }

app_allergen:
  path: /allergens/{dish}
  methods: GET
  defaults: { _controller: AppBundle:Api:allergensByDish, dish: '-' }

app_dishes:
  path: /dishes/{allergen}
  methods: GET
  defaults: { _controller: AppBundle:Api:dishesByAllergen, allergen: '-' }

app_create_dish:
  path: /dish/new
  methods: POST
  defaults: { _controller: AppBundle:Api:createDish }

app_create_ingredient:
  path: /ingredient/new
  methods: POST
  defaults: { _controller: AppBundle:Api:createIngredient }

app_create_allergen:
  path: /allergen/new
  methods: POST
  defaults: { _controller: AppBundle:Api:createAllergen }
