app_index:
  path: /
  methods: GET
  defaults: { _controller: AppBundle:Default:index }

app_allergen:
  path: /allergens/{dish}
  methods: GET
  defaults: { _controller: AppBundle:Api:allergensByDish, dish: '-' }

app_dishes:
  path: /dishes/{allergen}
  methods: GET
  defaults: { _controller: AppBundle:Api:dishesByAllergen, allergen: '-' }

app_create_dish:
  path: /dishes/new
  methods: POST
  defaults: { _controller: AppBundle:Api:createDish }
